apiVersion: v1
kind: Service
metadata:
  name: sampleapp-image-service
spec:
  selector:
    app: sampleapp-image
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
