on: push
jobs:
  first-jobb:
    runs-on: ubuntu-latest 
    steps:
      - run: npm install -g npm@latest
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v2
      - run: npm install
      - run: node index.js
      
  
