on: push
jobs:
  first-jobb:
    runs-on: ubuntu-latest 
    steps:
      - name: install npm latest version
        run: npm install -g npm@latest
      - name: Check node version
        run: node --version
      - name: Check npm version
        run: npm --version
      - uses: actions/checkout@v2
      - name: Installing additional dependencies
        run: npm install
      - name: running index.js file
        run: node index.js
      
  
